### PR TITLE
Amb 52 monitoring and alerting with statuscake

### PR DESCRIPTION
**Pull request by artronics**
Add statuscake deployment for two endpoints, `_status` and `_ping`.
`_status` should return backend status and `_ping` returns proxy.

### CODE REVIEW

**Comment by Sourceless** [comment]
LGTM, but would like Matt to take a look as well to make sure it aligns with the work he's done on it

**Comment by Sourceless** [comment]
In addition BEFORE this gets merged, please deploy with this (you can set a module in e.g. personal demographics or hello-world to point to this branch) on internal-dev and make sure it's working

**Comment by artronics** [comment]
> In addition BEFORE this gets merged, please deploy with this (you can set a module in e.g. personal demographics or hello-world to point to this branch) on internal-dev and make sure it's working

This has been tested with the Helloworld service. With the new changes we wont see anything happening during namespaced deployment. So even if I add this to the PDS (in a new branch) it's not going to do anything.

**Comment by Sourceless** [comment]
For now restrict it to work in both the no-namespace case and the case where the namespace belongs to this ticket -- that should be sufficient to test that it all works

**Pull request closed without merging**
